{
 "title": "2. Query performance analysis (top-N)",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "top_n", "query": "10, 15, 20" },
   {
    "name": "cluster_name",
    "label": "Cluster name",
    "query": {
     "query": "label_values(pgwatch_settings_configured,cluster)"
    }
   },
   {
    "name": "node_name",
    "label": "Node name",
    "query": {
     "query": "label_values(pgwatch_settings_configured{cluster=\"$cluster_name\"},node_name)"
    }
   },
   {
    "name": "db_name",
    "label": "DB name",
    "query": {
     "query": "label_values(pgwatch_pg_database_wraparound_age_datfrozenxid{cluster=\"$cluster_name\", node_name=\"$node_name\", datname!=\"template1\"},datname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "pg_stat_statements",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "columns": [
        { "selector": "queryid", "text": "Query ID", "type": "string" },
        { "selector": "duration_seconds", "text": "Duration (seconds)", "type": "number" },
        { "selector": "calls", "text": "Calls", "type": "number" },
        { "selector": "calls_per_sec", "text": "Calls/sec", "type": "number" },
        { "selector": "total_time", "text": "Total Time (ms)", "type": "number" },
        { "selector": "total_time_per_sec", "text": "Total Time/sec (ms/s)", "type": "number" },
        { "selector": "total_time_per_call", "text": "Time/call (ms)", "type": "number" },
        { "selector": "rows", "text": "Rows", "type": "number" },
        { "selector": "rows_per_sec", "text": "Rows/sec", "type": "number" },
        { "selector": "rows_per_call", "text": "Rows/call", "type": "number" },
        { "selector": "shared_blks_hit", "text": "Shared Blocks Hit", "type": "number" },
        { "selector": "shared_blks_hit_per_sec", "text": "Shared Blocks Hit/sec", "type": "number" },
        { "selector": "shared_blks_hit_per_call", "text": "Shared Blocks Hit/call", "type": "number" },
        { "selector": "shared_blks_read", "text": "Shared Blocks Read", "type": "number" },
        { "selector": "shared_blks_read_per_sec", "text": "Shared Blocks Read/sec", "type": "number" },
        { "selector": "shared_blks_read_per_call", "text": "Shared Blocks Read/call", "type": "number" },
        { "selector": "shared_blks_dirtied", "text": "Shared Blocks Dirtied", "type": "number" },
        { "selector": "shared_blks_dirtied_per_sec", "text": "Shared Blocks Dirtied/sec", "type": "number" },
        { "selector": "shared_blks_dirtied_per_call", "text": "Shared Blocks Dirtied/call", "type": "number" },
        { "selector": "shared_blks_written", "text": "Shared Blocks Written", "type": "number" },
        { "selector": "shared_blks_written_per_sec", "text": "Shared Blocks Written/sec", "type": "number" },
        { "selector": "shared_blks_written_per_call", "text": "Shared Blocks Written/call", "type": "number" },
        { "selector": "blk_read_time", "text": "Block Read Time (ms)", "type": "number" },
        { "selector": "blk_read_time_per_sec", "text": "Block Read Time/sec (ms)", "type": "number" },
        { "selector": "blk_read_time_per_call", "text": "Block Read Time/call (ms)", "type": "number" },
        { "selector": "blk_write_time", "text": "Block Write Time (ms)", "type": "number" },
        { "selector": "blk_write_time_per_sec", "text": "Block Write Time/sec (ms)", "type": "number" },
        { "selector": "blk_write_time_per_call", "text": "Block Write Time/call (ms)", "type": "number" }
       ],
       "parser": "backend",
       "source": "url",
       "type": "csv",
       "url": "http://flask-pgss-api:5000/pgss_metrics/csv",
       "url_options": {
        "data": "",
        "method": "GET",
        "params": [
         { "key": "time_start", "value": "${__from:date}" },
         { "key": "time_end", "value": "${__to:date}" },
         { "key": "db_name", "value": "target_database" }
        ]
       }
      }
     ]
    }
   ]
  },
  { "title": "Graph Call Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Top $top_n statements by calls (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "topk($top_n, irate(pgwatch_pg_stat_statements_calls{cluster='$cluster_name', node_name='$node_name', datname=\"$db_name\"}[$__rate_interval]))",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Top $top_n statements by execution time (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk($top_n, irate(pgwatch_pg_stat_statements_exec_time_total{cluster='$cluster_name', node_name='$node_name', datname=\"$db_name\"}[$__rate_interval]))",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Top $top_n statements by execution time per call (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk($top_n, irate(pgwatch_pg_stat_statements_exec_time_total{cluster='$cluster_name', node_name='$node_name', datname=\"$db_name\"}[$__rate_interval])/irate(pgwatch_pg_stat_statements_calls{cluster='$cluster_name', node_name='$node_name', datname=\"$db_name\"}[$__rate_interval]))",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Top $top_n statements by rows (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "topk($top_n, irate(pgwatch_pg_stat_statements_rows{cluster='$cluster_name', node_name='$node_name', datname=\"$db_name\"}[$__rate_interval]))",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Top $top_n statements by rows per call (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "topk($top_n, irate(pgwatch_pg_stat_statements_rows{cluster='$cluster_name', node_name='$node_name', datname=\"$db_name\"}[$__rate_interval])/irate(pgwatch_pg_stat_statements_calls{cluster='$cluster_name', node_name='$node_name', datname=\"$db_name\"}[$__rate_interval]))",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Top $top_n statements by shared_blks_hit (in bytes) (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk($top_n, irate(pgwatch_pg_stat_statements_shared_bytes_hit_total{cluster='$cluster_name', node_name='$node_name', datname=\"$db_name\"}[$__rate_interval]))",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Top $top_n statements by shared_blks_hit (in bytes) per call (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk($top_n, irate(pgwatch_pg_stat_statements_shared_bytes_hit_total{cluster='$cluster_name', node_name='$node_name', datname=\"$db_name\"}[$__rate_interval])/irate(pgwatch_pg_stat_statements_calls{cluster='$cluster_name', node_name='$node_name', datname=\"$db_name\"}[$__rate_interval]))",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Top $top_n statements by WAL bytes (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk($top_n, irate(pgwatch_pg_stat_statements_wal_bytes{cluster='$cluster_name', node_name='$node_name', datname=\"$db_name\"}[$__rate_interval]))",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Top $top_n statements by WAL bytes per call (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk($top_n, irate(pgwatch_pg_stat_statements_wal_bytes{cluster='$cluster_name', node_name='$node_name', datname=\"$db_name\"}[$__rate_interval])/irate(pgwatch_pg_stat_statements_calls{cluster='$cluster_name', node_name='$node_name', datname=\"$db_name\"}[$__rate_interval]))",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Top $top_n statements by WAL fpi (in bytes) (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "topk($top_n, irate(pgwatch_pg_stat_statements_wal_fpi{cluster='$cluster_name', node_name='$node_name', datname=\"$db_name\"}[$__rate_interval]))",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Top $top_n statements by WAL fpi per call (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "topk($top_n, irate(pgwatch_pg_stat_statements_wal_fpi{cluster='$cluster_name', node_name='$node_name', datname=\"$db_name\"}[$__rate_interval])/irate(pgwatch_pg_stat_statements_calls{cluster='$cluster_name', node_name='$node_name', datname=\"$db_name\"}[$__rate_interval]))",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Top $top_n statements by temp bytes read (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk($top_n, irate(pgwatch_pg_stat_statements_temp_bytes_read{cluster='$cluster_name', node_name='$node_name', datname=\"$db_name\"}[$__rate_interval]))",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Top $top_n statements by temp bytes read per call (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk($top_n, irate(pgwatch_pg_stat_statements_temp_bytes_read{cluster='$cluster_name', node_name='$node_name', datname=\"$db_name\"}[$__rate_interval])/irate(pgwatch_pg_stat_statements_calls{cluster='$cluster_name', node_name='$node_name', datname=\"$db_name\"}[$__rate_interval]))",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Top $top_n statements by temp bytes written (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk($top_n, irate(pgwatch_pg_stat_statements_temp_bytes_written{cluster='$cluster_name', node_name='$node_name', datname=\"$db_name\"}[$__rate_interval]))",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Top $top_n statements by temp bytes written per call (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk($top_n, irate(pgwatch_pg_stat_statements_temp_bytes_written{cluster='$cluster_name', node_name='$node_name', datname=\"$db_name\"}[$__rate_interval])/irate(pgwatch_pg_stat_statements_calls{cluster='$cluster_name', node_name='$node_name', datname=\"$db_name\"}[$__rate_interval]))",
     "legendFormat": "{{queryid}}"
    }
   ]
  }
 ]
}