{
 "title": "10. Aggregated index analysis",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "top_n", "query": "10, 15, 20" },
   {
    "name": "cluster_name",
    "label": "Cluster name",
    "query": {
     "query": "label_values(pgwatch_settings_configured,cluster)"
    }
   },
   {
    "name": "node_name",
    "label": "Node name",
    "query": {
     "query": "label_values(pgwatch_settings_configured{cluster=\"$cluster_name\"},node_name)"
    }
   },
   {
    "name": "db_name",
    "label": "DB name",
    "query": {
     "query": "label_values(pgwatch_pg_database_wraparound_age_datfrozenxid{cluster=\"$cluster_name\", node_name=\"$node_name\", datname!=\"template1\"},datname)"
    }
   },
   {
    "name": "schema_name",
    "query": {
     "query": "label_values(pgwatch_pg_stat_all_indexes_idx_scan,schemaname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Detailed table view", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "columns": [
      { "selector": "bloat_pct", "text": "", "type": "number" },
      { "selector": "bloat_size", "text": "", "type": "number" },
      { "selector": "fillfactor", "text": "", "type": "number" },
      { "selector": "idxname", "text": "", "type": "string" },
      { "selector": "schemaname", "text": "", "type": "string" },
      { "selector": "tblname", "text": "", "type": "string" },
      { "selector": "real_size_mib", "text": "", "type": "number" },
      { "selector": "is_na", "text": "", "type": "number" }
     ],
     "filterExpression": "is_na<1 && bloat_pct>0",
     "parser": "backend",
     "source": "url",
     "type": "csv",
     "url": "http://flask-pgss-api:5000/btree_bloat/csv",
     "url_options": {
      "data": "",
      "method": "GET",
      "params": [
       { "key": "cluster_name", "value": "$cluster_name" },
       { "key": "node_name", "value": "$node_name" },
       { "key": "db_name", "value": "$db_name" }
      ]
     }
    }
   ]
  },
  { "title": "Index size stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Top $top_n indexes by size",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk($top_n, pgwatch_pg_class_total_relation_size_bytes{relkind=\"105\", schemaname=~\"$schema_name\", datname=\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"})",
     "legendFormat": "{{schemaname}}.{{relname}}"
    }
   ]
  },
  {
   "title": "Top $top_n indexes by size change rate (absolute)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk($top_n, irate(pgwatch_pg_class_total_relation_size_bytes{relkind=\"105\", schemaname=~\"$schema_name\", datname=\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"}[$__rate_interval]))",
     "legendFormat": "{{schemaname}}.{{relname}}"
    }
   ]
  },
  {
   "title": "B-tree index estimated bloat stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 }
  },
  {
   "title": "Top $top_n indexes by estimated bloat %",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk($top_n, pgwatch_pg_btree_bloat_bloat_pct{cluster='$cluster_name', node_name='$node_name', datname=\"$db_name\"})",
     "legendFormat": "{{schemaname}}.{{tblname}}.{{idxname}}"
    }
   ]
  },
  {
   "title": "Top $top_n indexes by estimated bloat size",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk($top_n, pgwatch_pg_btree_bloat_bloat_size{cluster='$cluster_name', node_name='$node_name', datname=\"$db_name\"})",
     "legendFormat": "{{schemaname}}.{{tblname}}.{{idxname}}"
    }
   ]
  },
  { "title": "Index usage stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Top $top_n indexes by scan rate",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk($top_n, irate(pgwatch_pg_stat_all_indexes_idx_scan{schemaname=~\"$schema_name\", datname=\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"}[$__rate_interval]))",
     "legendFormat": "{{schemaname}}.{{relname}}.{{indexrelname}}"
    }
   ]
  },
  {
   "title": "Top $top_n indexes by tuples read rate",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk($top_n, irate(pgwatch_pg_stat_all_indexes_idx_tup_read{schemaname=~\"$schema_name\", datname=\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"}[$__rate_interval]))",
     "legendFormat": "{{schemaname}}.{{relname}}.{{indexrelname}}"
    }
   ]
  },
  {
   "title": "Top $top_n indexes by tuples fetched rate",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk($top_n, irate(pgwatch_pg_stat_all_indexes_idx_tup_fetch{schemaname=~\"$schema_name\", datname=\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"}[$__rate_interval]))",
     "legendFormat": "{{schemaname}}.{{relname}}.{{indexrelname}}"
    }
   ]
  },
  { "title": "Index IO stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Top $top_n indexes by shared block hits",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk($top_n, irate(pgwatch_pg_statio_all_indexes_idx_blks_hit{schemaname=~\"$schema_name\", datname=\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"}[$__rate_interval]) * on() group_left() last_over_time(pgwatch_settings_numeric_value{datname=\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\", setting_name=\"block_size\"}[1h]))",
     "legendFormat": "{{schemaname}}.{{relname}}.{{indexrelname}}"
    }
   ]
  },
  {
   "title": "Top $top_n indexes by shared block reads",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk($top_n, irate(pgwatch_pg_statio_all_indexes_idx_blks_read{schemaname=~\"$schema_name\", datname=\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"}[$__rate_interval]) * on() group_left() last_over_time(pgwatch_settings_numeric_value{datname=\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\", setting_name=\"block_size\"}[1h]))",
     "legendFormat": "{{schemaname}}.{{relname}}.{{indexrelname}}"
    }
   ]
  },
  {
   "title": "Top $top_n indexes by shared block hit ratio",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk($top_n, irate(pgwatch_pg_statio_all_indexes_idx_blks_hit{schemaname=~\"$schema_name\", datname=\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"}[$__rate_interval]) / (irate(pgwatch_pg_statio_all_indexes_idx_blks_hit{schemaname=~\"$schema_name\", datname=\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"}[$__rate_interval]) + irate(pgwatch_pg_statio_all_indexes_idx_blks_read{schemaname=~\"$schema_name\", datname=\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"}[$__rate_interval])))",
     "legendFormat": "{{schemaname}}.{{relname}}.{{indexrelname}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 99 },
   "options": {
    "content": "<h1>\n  Brought to you by <a href=\"https://postgres.ai\">PostgresAI</a>\n  <img src=\"https://postgres.ai/img/logo.svg\" alt=\"Postgres.AI\" style=\"height: 2em; vertical-align: middle; margin-left: 0.3em;\">\n</h1>\n"
   }
  }
 ]
}