{
 "title": "08. Index health  -- \"Metrics are collected (part of health check); dashboard – TODO\"",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "top_n", "query": "10, 15, 20" },
   {
    "name": "cluster_name",
    "label": "Cluster name",
    "query": {
     "query": "label_values(pgwatch_settings_configured,cluster)"
    }
   },
   {
    "name": "node_name",
    "label": "Node name",
    "query": {
     "query": "label_values(pgwatch_settings_configured{cluster=\"$cluster_name\"},node_name)"
    }
   },
   {
    "name": "db_name",
    "label": "DB name",
    "query": {
     "query": "label_values(pgwatch_pg_database_wraparound_age_datfrozenxid{cluster=\"$cluster_name\", node_name=\"$node_name\", datname!=\"template1\"},datname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Detailed index view", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "columns": [
      { "selector": "bloat_pct", "text": "", "type": "number" },
      { "selector": "bloat_size", "text": "", "type": "number" },
      { "selector": "fillfactor", "text": "", "type": "number" },
      { "selector": "idxname", "text": "", "type": "string" },
      { "selector": "schemaname", "text": "", "type": "string" },
      { "selector": "tblname", "text": "", "type": "string" },
      { "selector": "real_size_mib", "text": "", "type": "number" },
      { "selector": "is_na", "text": "", "type": "number" }
     ],
     "filterExpression": "is_na<1 && bloat_pct>0",
     "parser": "backend",
     "source": "url",
     "type": "csv",
     "url": "http://flask-pgss-api:5000/btree_bloat/csv",
     "url_options": {
      "data": "",
      "method": "GET",
      "params": [
       { "key": "cluster_name", "value": "$cluster_name" },
       { "key": "node_name", "value": "$node_name" },
       { "key": "db_name", "value": "$db_name" }
      ]
     }
    }
   ]
  },
  { "title": "Top $top_n index analysis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Top $top_n indexes by estimated bloat %",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk($top_n, pgwatch_pg_btree_bloat_bloat_pct{cluster='$cluster_name', node_name='$node_name', datname=\"$db_name\"})",
     "legendFormat": "{{schemaname}}.{{tblname}}.{{idxname}}"
    }
   ]
  },
  {
   "title": "Top $top_n indexes by estimated bloat size",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk($top_n, pgwatch_pg_btree_bloat_bloat_size{cluster='$cluster_name', node_name='$node_name', datname=\"$db_name\"})",
     "legendFormat": "{{schemaname}}.{{tblname}}.{{idxname}}"
    }
   ]
  },
  {
   "title": "Top $top_n indexes by size",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk($top_n, pgwatch_pg_btree_bloat_real_size_mib{cluster='$cluster_name', node_name='$node_name', datname=\"$db_name\"})*1024*1024",
     "legendFormat": "{{schemaname}}.{{tblname}}.{{idxname}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 53 },
   "options": {
    "content": "<h1>\n  Brought to you by <a href=\"https://postgres.ai\">PostgresAI</a>\n  <img src=\"https://postgres.ai/img/logo.svg\" alt=\"Postgres.AI\" style=\"height: 2em; vertical-align: middle; margin-left: 0.3em;\">\n</h1>\n"
   }
  }
 ]
}