{
 "title": "PoC",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "agg_interval", "query": "10s,1m,5m,1h" }
  ]
 },
 "panels": [
  {
   "title": "Average query runtime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(pgwatch_stat_statements_total_time[$agg_interval])) / sum(rate(pgwatch_stat_statements_calls[$agg_interval]))",
     "legendFormat": "Runtime"
    }
   ]
  },
  {
   "title": "pg_stat_statements_calls_to_query",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "pgwatch_pg_stat_statements_calls_calls",
     "legendFormat": "__auto"
    },
    {
     "rawSql": "SELECT\n  DISTINCT (data ->> 'queryid') as queryid,\n  data ->> 'query' as query_text\nFROM\n  pgss_queryid_queries\nWHERE\n  $__timeFilter(time)"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "pgwatch_backends_idleintransaction",
     "legendFormat": "Idle-in-transaction"
    },
    { "expr": "pgwatch_backends_idle", "legendFormat": "Idle" },
    { "expr": "pgwatch_backends_active", "legendFormat": "Active" },
    {
     "expr": "pgwatch_settings_max_connections",
     "legendFormat": "Max connections"
    },
    { "expr": "pgwatch_backends_total", "legendFormat": "Total" },
    { "expr": "pgwatch_backends_waiting ", "legendFormat": "Waiting" }
   ]
  }
 ]
}