{
 "title": "4. Wait event analysis (Active Session History)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "wait_event_type",
    "label": "Wait event type",
    "query": {
     "query": "label_values(pgwatch_wait_events_total,wait_event_type)"
    }
   },
   {
    "name": "wait_event",
    "label": "Wait event",
    "query": {
     "query": "label_values(pgwatch_wait_events_total{wait_event_type=~\"$wait_event_type\"},wait_event)"
    }
   },
   {
    "name": "cluster_name",
    "label": "Cluster name",
    "query": {
     "query": "label_values(pgwatch_settings_configured,cluster)"
    }
   },
   {
    "name": "node_name",
    "label": "Node name",
    "query": {
     "query": "label_values(pgwatch_settings_configured{cluster=\"$cluster_name\"},node_name)"
    }
   },
   {
    "name": "db_name",
    "label": "DB name",
    "query": {
     "query": "label_values(pgwatch_pg_database_wraparound_age_datfrozenxid{cluster=\"$cluster_name\", node_name=\"$node_name\", datname!=\"template1\"},datname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Active session history",
   "type": "timeseries",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (wait_event_type) (pgwatch_wait_events_total{cluster='$cluster_name', node_name='$node_name', datname=\"$db_name\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (wait_event_type) (pgwatch_wait_events_total{datname=\"server_process\", wait_event_type!~\".*- Activity.*\"})",
     "legendFormat": "Postgres - {{wait_event_type}}"
    },
    {
     "expr": "sum by (wait_event_type) (pgwatch_wait_events_total{datname=\"server_process\", wait_event_type=~\".*- Activity.*\"})",
     "legendFormat": "Idle Internal - {{wait_event_type}}"
    },
    {
     "expr": "sum by (event_type) (irate(pgwatch_wait_events_sampling_total[$__rate_interval]))>0",
     "legendFormat": " {{event_type}}"
    }
   ]
  },
  {
   "title": "Active session history by event type",
   "type": "timeseries",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by (wait_event_type, wait_event) (pgwatch_wait_events_total{cluster='$cluster_name', node_name='$node_name', datname=\"$db_name\", wait_event_type=~\"$wait_event_type\"})",
     "legendFormat": "{{wait_event_type}} - {{wait_event}}"
    }
   ]
  },
  {
   "title": "Active session history by event type and event",
   "type": "timeseries",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum by (wait_event_type, wait_event, query_id) (pgwatch_wait_events_total{cluster='$cluster_name', node_name='$node_name', datname=\"$db_name\", wait_event_type=~\"$wait_event_type\", wait_event=~\"$wait_event\"})",
     "legendFormat": "{{wait_event_type}} - {{wait_event}} - {{query_id}}"
    }
   ]
  }
 ]
}