{
 "title": "09. Top tables overview",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster_name",
    "label": "Cluster name",
    "query": {
     "query": "label_values(pgwatch_settings_configured,cluster)"
    }
   },
   {
    "name": "node_name",
    "label": "Node name",
    "query": {
     "query": "label_values(pgwatch_settings_configured{cluster=\"$cluster_name\"},node_name)"
    }
   },
   {
    "name": "db_name",
    "label": "DB name",
    "query": {
     "query": "label_values(pgwatch_pg_database_wraparound_age_datfrozenxid{cluster=\"$cluster_name\", node_name=\"$node_name\", datname!=\"template1\"},datname)"
    }
   },
   {
    "name": "schema_name",
    "label": "Schema name",
    "query": {
     "query": "label_values(pgwatch_pg_class_relation_size_bytes,schemaname)"
    }
   },
   { "name": "top_n", "label": "Top N tables", "query": "5,10,15,20" }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Top $top_n tables by size",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk($top_n, pgwatch_pg_class_total_relation_size_bytes{relkind=\"114\", schemaname=~\"$schema_name\", datname=\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"})",
     "legendFormat": "{{schemaname}}.{{relname}}"
    }
   ]
  },
  {
   "title": "Top $top_n tables by size change rate",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk($top_n, irate(pgwatch_pg_class_total_relation_size_bytes{relkind=\"114\", schemaname=~\"$schema_name\", datname=\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"}[$__rate_interval]))",
     "legendFormat": "{{schemaname}}.{{relname}}"
    }
   ]
  },
  {
   "title": "Top $top_n tables by estimated bloat %",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk($top_n, pgwatch_pg_table_bloat_bloat_pct{schemaname=~\"$schema_name\", datname=\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"})",
     "legendFormat": "{{schemaname}}.{{tblname}}"
    }
   ]
  },
  {
   "title": "Top $top_n tables by estimated bloat size",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk($top_n, pgwatch_pg_table_bloat_bloat_size{schemaname=~\"$schema_name\", datname=\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"})",
     "legendFormat": "{{schemaname}}.{{tblname}}"
    }
   ]
  },
  { "title": "Tuple stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Tuple operations (aggregated)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(irate(pgwatch_table_stats_n_tup_ins{datname=\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\", schema=~\"$schema_name\"}[$__rate_interval]))",
     "legendFormat": "Inserts"
    },
    {
     "expr": "sum(irate(pgwatch_table_stats_n_tup_upd{datname=\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\", schema=~\"$schema_name\"}[$__rate_interval]))",
     "legendFormat": "Updates"
    },
    {
     "expr": "sum(irate(pgwatch_table_stats_n_tup_hot_upd{datname=\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\", schema=~\"$schema_name\"}[$__rate_interval]))",
     "legendFormat": "HOT Updates"
    },
    {
     "expr": "sum(irate(pgwatch_table_stats_n_tup_del{datname=\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\", schema=~\"$schema_name\"}[$__rate_interval]))",
     "legendFormat": "Deletes"
    }
   ]
  },
  {
   "title": "Tuple operations (%) (Aggregated)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(pgwatch_table_stats_n_tup_ins{datname=\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\", schema=~\"$schema_name\"}[$__rate_interval]))",
     "legendFormat": "Inserts"
    },
    {
     "expr": "sum(irate(pgwatch_table_stats_n_tup_upd{datname=\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\", schema=~\"$schema_name\"}[$__rate_interval]))",
     "legendFormat": "Updates"
    },
    {
     "expr": "sum(irate(pgwatch_table_stats_n_tup_hot_upd{datname=\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\", schema=~\"$schema_name\"}[$__rate_interval]))",
     "legendFormat": "HOT Updates"
    },
    {
     "expr": "sum(irate(pgwatch_table_stats_n_tup_del{datname=\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\", schema=~\"$schema_name\"}[$__rate_interval]))",
     "legendFormat": "Deletes"
    }
   ]
  },
  {
   "title": "Top $top_n tables by inserts/sec",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "topk($top_n, sum by(schema, table_name, table_full_name) (irate(pgwatch_table_stats_n_tup_ins{datname=\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\", schema=~\"$schema_name\"}[$__rate_interval])))",
     "legendFormat": "{{table_full_name}}"
    }
   ]
  },
  {
   "title": "Top $top_n tables by updates/sec",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk($top_n, sum by(schema, table_name, table_full_name) (irate(pgwatch_table_stats_n_tup_upd{datname=\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\", schema=~\"$schema_name\"}[$__rate_interval])))",
     "legendFormat": "{{table_full_name}}"
    }
   ]
  },
  {
   "title": "Top $top_n tables by deletes/sec",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk($top_n, sum by(schema, table_name, table_full_name) (irate(pgwatch_table_stats_n_tup_del{datname=\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\", schema=~\"$schema_name\"}[$__rate_interval])))",
     "legendFormat": "{{table_full_name}}"
    }
   ]
  },
  {
   "title": "Top $top_n tables by HOT updates/sec",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk($top_n, sum by(schema, table_name, table_full_name) (irate(pgwatch_table_stats_n_tup_hot_upd{datname=\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\", schema=~\"$schema_name\"}[$__rate_interval])))",
     "legendFormat": "{{table_full_name}}"
    }
   ]
  },
  {
   "title": "Top $top_n tables by Non-HOT updates/sec",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk($top_n, sum by(schema, table_name, table_full_name) (irate(pgwatch_table_stats_n_tup_upd{datname=\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\", schema=~\"$schema_name\"}[$__rate_interval]) - irate(pgwatch_table_stats_n_tup_hot_upd{datname=\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\", schema=~\"$schema_name\"}[$__rate_interval])))",
     "legendFormat": "{{table_full_name}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 78 },
   "options": {
    "content": "<h1>\n  Brought to you by <a href=\"https://postgres.ai\">PostgresAI</a>\n  <img src=\"https://postgres.ai/img/logo.svg\" alt=\"Postgres.AI\" style=\"height: 2em; vertical-align: middle; margin-left: 0.3em;\">\n</h1>\n"
   }
  }
 ]
}