{
 "title": "11. Single table analysis",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster_name",
    "label": "Cluster name",
    "query": {
     "query": "label_values(pgwatch_settings_configured,cluster)"
    }
   },
   {
    "name": "node_name",
    "label": "Node name",
    "query": {
     "query": "label_values(pgwatch_settings_configured{cluster=\"$cluster_name\"},node_name)"
    }
   },
   {
    "name": "db_name",
    "label": "DB name",
    "query": {
     "query": "label_values(pgwatch_pg_database_wraparound_age_datfrozenxid{cluster=\"$cluster_name\", node_name=\"$node_name\", datname!=\"template1\"},datname)"
    }
   },
   {
    "name": "schema_name",
    "label": "Schema name",
    "query": {
     "query": "label_values(pgwatch_table_stats_n_tup_ins,schema)"
    }
   },
   {
    "name": "table_name",
    "label": "Table name",
    "query": {
     "query": "label_values(pgwatch_table_stats_n_tup_ins{schema=\"$schema_name\"},table_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Table size",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pgwatch_pg_class_total_relation_size_bytes{relkind=\"114\", schemaname=\"$schema_name\", relname=\"$table_name\"}",
     "legendFormat": "{{schemaname}}.{{relname}}"
    }
   ]
  },
  {
   "title": "Table size change rate",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(pgwatch_pg_class_total_relation_size_bytes{relkind=\"114\", schemaname=\"$schema_name\", relname=\"$table_name\"}[$__rate_interval])",
     "legendFormat": "{{schemaname}}.{{relname}}"
    }
   ]
  },
  { "title": "Bloat stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Bloat size",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pgwatch_pg_table_bloat_bloat_size{schemaname=\"$schema_name\", tblname=\"$table_name\"}",
     "legendFormat": "{{schemaname}}.{{tblname}}"
    }
   ]
  },
  {
   "title": "Bloat %",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "pgwatch_pg_table_bloat_bloat_pct{schemaname=\"$schema_name\", tblname=\"$table_name\"}",
     "legendFormat": "{{schemaname}}.{{tblname}}"
    }
   ]
  },
  { "title": "Tuple stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Tuple operations",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (node_name, table_full_name, dbname, cluster) (irate(pgwatch_table_stats_n_tup_ins{datname=\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\", schema=\"$schema_name\", table_name=\"$table_name\"}[$__rate_interval]))",
     "legendFormat": "Inserts"
    },
    {
     "expr": "sum by (node_name, table_full_name, dbname, cluster) (irate(pgwatch_table_stats_n_tup_upd{datname=\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\", schema=\"$schema_name\", table_name=\"$table_name\"}[$__rate_interval]))",
     "legendFormat": "Updates"
    },
    {
     "expr": "sum by (node_name, table_full_name, dbname, cluster) (irate(pgwatch_table_stats_n_tup_hot_upd{datname=\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\", schema=\"$schema_name\", table_name=\"$table_name\"}[$__rate_interval]))",
     "legendFormat": "HOT Updates"
    },
    {
     "expr": "sum by (node_name, table_full_name, dbname, cluster) (irate(pgwatch_table_stats_n_tup_del{datname=\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\", schema=\"$schema_name\", table_name=\"$table_name\"}[$__rate_interval]))",
     "legendFormat": "Deletes"
    }
   ]
  },
  {
   "title": "Tuple operations (%) (Aggregated)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(pgwatch_table_stats_n_tup_ins{datname=\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\", schema=~\"$schema_name\", table_name=~\"$table_name\"}[$__rate_interval]))",
     "legendFormat": "Inserts"
    },
    {
     "expr": "sum(irate(pgwatch_table_stats_n_tup_upd{datname=\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\", schema=~\"$schema_name\", table_name=~\"$table_name\"}[$__rate_interval]))",
     "legendFormat": "Updates"
    },
    {
     "expr": "sum(irate(pgwatch_table_stats_n_tup_hot_upd{datname=\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\", schema=~\"$schema_name\", table_name=~\"$table_name\"}[$__rate_interval]))",
     "legendFormat": "HOT Updates"
    },
    {
     "expr": "sum(irate(pgwatch_table_stats_n_tup_del{datname=\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\", schema=~\"$schema_name\", table_name=~\"$table_name\"}[$__rate_interval]))",
     "legendFormat": "Deletes"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 74 },
   "options": {
    "content": "<h1>\n  Brought to you by <a href=\"https://postgres.ai\">PostgresAI</a>\n  <img src=\"https://postgres.ai/img/logo.svg\" alt=\"Postgres.AI\" style=\"height: 2em; vertical-align: middle; margin-left: 0.3em;\">\n</h1>\n"
   }
  }
 ]
}