{
 "title": "05. Backups and DR",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Archive success and errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "irate(pgwatch_archive_lag_archived_count[$__rate_interval])",
     "legendFormat": "Archived count"
    },
    {
     "expr": "irate(pgwatch_archive_lag_failed_count[$__rate_interval])",
     "legendFormat": "Failed count"
    }
   ]
  },
  {
   "title": "WAL archive success rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(pgwatch_archive_lag_archived_count[$__rate_interval])/(irate(pgwatch_archive_lag_archived_count[$__rate_interval])+irate(pgwatch_archive_lag_failed_count[$__rate_interval]))",
     "legendFormat": "Percentage of succesful operations"
    }
   ]
  },
  {
   "title": "Archive lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pgwatch_archive_lag_current_lsn_numeric - pgwatch_archive_lag_archived_wal_finish_lsn_numeric",
     "legendFormat": "Archive lag"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 16 },
   "options": {
    "content": "<h1>\n  Brought to you by <a href=\"https://postgres.ai\">PostgresAI</a>\n  <img src=\"https://postgres.ai/img/logo.svg\" alt=\"Postgres.AI\" style=\"height: 2em; vertical-align: middle; margin-left: 0.3em;\">\n</h1>\n"
   }
  }
 ]
}