{
 "title": "3. Single queryid analysis",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "query_id" },
   {
    "name": "cluster_name",
    "label": "Cluster name",
    "query": {
     "query": "label_values(pgwatch_settings_configured,cluster)"
    }
   },
   {
    "name": "node_name",
    "label": "Node name",
    "query": {
     "query": "label_values(pgwatch_settings_configured{cluster=\"$cluster_name\"},node_name)"
    }
   },
   {
    "name": "db_name",
    "label": "DB name",
    "query": {
     "query": "label_values(pgwatch_pg_database_wraparound_age_datfrozenxid{cluster=\"$cluster_name\", node_name=\"$node_name\", datname!=\"template1\"},datname)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT data ->> 'query' as \"Query text\"\nFROM pgss_queryid_queries\nWHERE (data ->> 'queryid') = '$query_id' LIMIT 1\n"
    }
   ]
  },
  {
   "title": "Active session history",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by (wait_event_type) (pgwatch_wait_events_total{query_id=\"$query_id\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (event_type) (irate(pgwatch_wait_events_sampling_total[$__rate_interval]))>0",
     "legendFormat": " {{event_type}}"
    }
   ]
  },
  {
   "title": "Calls (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "irate(pgwatch_pg_stat_statements_calls{cluster=\"$cluster_name\", node_name=\"$node_name\", datname=\"$db_name\", queryid=\"$query_id\"}[$__rate_interval])",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Execution time (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(pgwatch_pg_stat_statements_exec_time_total{cluster=\"$cluster_name\", node_name=\"$node_name\", datname=\"$db_name\", queryid=\"$query_id\"}[$__rate_interval])",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Top $top_n statements by execution time per call (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(pgwatch_pg_stat_statements_exec_time_total{cluster=\"$cluster_name\", node_name=\"$node_name\", datname=\"$db_name\", queryid=\"$query_id\"}[$__rate_interval])/irate(pgwatch_pg_stat_statements_calls{cluster=\"$cluster_name\", node_name=\"$node_name\", datname=\"$db_name\", queryid=\"$query_id\"}[$__rate_interval])",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Rows (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "irate(pgwatch_pg_stat_statements_rows{cluster=\"$cluster_name\", node_name=\"$node_name\", datname=\"$db_name\", queryid=\"$query_id\"}[$__rate_interval])",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Rows per call (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "targets": [
    {
     "expr": "irate(pgwatch_pg_stat_statements_rows{cluster=\"$cluster_name\", node_name=\"$node_name\", datname=\"$db_name\", queryid=\"$query_id\"}[$__rate_interval])/irate(pgwatch_pg_stat_statements_calls{cluster=\"$cluster_name\", node_name=\"$node_name\", datname=\"$db_name\", queryid=\"$query_id\"}[$__rate_interval])",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "shared_blks_hit (in bytes) (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(pgwatch_pg_stat_statements_shared_bytes_hit_total{cluster=\"$cluster_name\", node_name=\"$node_name\", datname=\"$db_name\", queryid=\"$query_id\"}[$__rate_interval])",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "shared_blks_hit (in bytes) per call (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(pgwatch_pg_stat_statements_shared_bytes_hit_total{cluster=\"$cluster_name\", node_name=\"$node_name\", datname=\"$db_name\", queryid=\"$query_id\"}[$__rate_interval])/irate(pgwatch_pg_stat_statements_calls{cluster=\"$cluster_name\", node_name=\"$node_name\", datname=\"$db_name\", queryid=\"$query_id\"}[$__rate_interval])",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "WAL bytes (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(pgwatch_pg_stat_statements_wal_bytes{cluster=\"$cluster_name\", node_name=\"$node_name\", datname=\"$db_name\", queryid=\"$query_id\"}[$__rate_interval])",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "WAL bytes per call (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(pgwatch_pg_stat_statements_wal_bytes{cluster=\"$cluster_name\", node_name=\"$node_name\", datname=\"$db_name\", queryid=\"$query_id\"}[$__rate_interval])/irate(pgwatch_pg_stat_statements_calls{cluster=\"$cluster_name\", node_name=\"$node_name\", datname=\"$db_name\", queryid=\"$query_id\"}[$__rate_interval])",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "WAL fpi (in bytes) (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "targets": [
    {
     "expr": "irate(pgwatch_pg_stat_statements_wal_fpi{cluster=\"$cluster_name\", node_name=\"$node_name\", datname=\"$db_name\", queryid=\"$query_id\"}[$__rate_interval])",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "WAL fpi per call (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "targets": [
    {
     "expr": "irate(pgwatch_pg_stat_statements_wal_fpi{cluster=\"$cluster_name\", node_name=\"$node_name\", datname=\"$db_name\", queryid=\"$query_id\"}[$__rate_interval])/irate(pgwatch_pg_stat_statements_calls{cluster=\"$cluster_name\", node_name=\"$node_name\", datname=\"$db_name\", queryid=\"$query_id\"}[$__rate_interval])",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Temp bytes read (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(pgwatch_pg_stat_statements_temp_bytes_read{cluster=\"$cluster_name\", node_name=\"$node_name\", datname=\"$db_name\", queryid=\"$query_id\"}[$__rate_interval])",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Temp bytes read per call (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(pgwatch_pg_stat_statements_temp_bytes_read{cluster=\"$cluster_name\", node_name=\"$node_name\", datname=\"$db_name\", queryid=\"$query_id\"}[$__rate_interval])/irate(pgwatch_pg_stat_statements_calls{cluster=\"$cluster_name\", node_name=\"$node_name\", datname=\"$db_name\", queryid=\"$query_id\"}[$__rate_interval])",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Temp bytes written (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(pgwatch_pg_stat_statements_temp_bytes_written{cluster=\"$cluster_name\", node_name=\"$node_name\", datname=\"$db_name\", queryid=\"$query_id\"}[$__rate_interval])",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Temp bytes written per call (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(pgwatch_pg_stat_statements_temp_bytes_written{cluster=\"$cluster_name\", node_name=\"$node_name\", datname=\"$db_name\", queryid=\"$query_id\"}[$__rate_interval])/irate(pgwatch_pg_stat_statements_calls{cluster=\"$cluster_name\", node_name=\"$node_name\", datname=\"$db_name\", queryid=\"$query_id\"}[$__rate_interval])",
     "legendFormat": "{{queryid}}"
    }
   ]
  }
 ]
}