{
 "title": "Database Overview",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "ASH",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Host stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true
  },
  { "title": "Postgres stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "pgwatch_backends_idleintransaction",
     "legendFormat": "Idle-in-transaction"
    },
    { "expr": "pgwatch_backends_idle", "legendFormat": "Idle" },
    { "expr": "pgwatch_backends_active", "legendFormat": "Active" },
    { "expr": "pgwatch_backends_waiting ", "legendFormat": "Waiting" },
    {
     "expr": "pgwatch_settings_max_connections",
     "legendFormat": "Max connections"
    }
   ]
  },
  {
   "title": "Non-Idle Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "pgwatch_backends_idleintransaction",
     "legendFormat": "Idle-in-transaction"
    },
    { "expr": "pgwatch_backends_active", "legendFormat": "Active" },
    {
     "expr": "pgwatch_settings_max_connections",
     "legendFormat": "Max connections"
    }
   ]
  },
  {
   "title": "Calls (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(irate(pgwatch_stat_statements_calls[$__rate_interval]))",
     "legendFormat": "Calls"
    }
   ]
  },
  {
   "title": "TODO: Postgres logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(irate(pgwatch_db_stats_xact_rollback[$__rate_interval]))",
     "legendFormat": "Rollbacks"
    },
    {
     "expr": "sum(irate(pgwatch_db_stats_xact_commit[$__rate_interval]))",
     "legendFormat": "Commits"
    }
   ]
  },
  {
   "title": "Commit ration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(irate(pgwatch_db_stats_xact_commit[$__rate_interval]))/(sum(irate(pgwatch_db_stats_xact_commit[$__rate_interval]))+sum(irate(pgwatch_db_stats_xact_rollback[$__rate_interval]))) * 100",
     "legendFormat": "Commits"
    }
   ]
  },
  {
   "title": "Statements total time (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "sec/sec" } },
   "targets": [
    {
     "expr": "sum(irate(pgwatch_stat_statements_calls_total_time[$__rate_interval]))",
     "legendFormat": "Calls"
    }
   ]
  },
  {
   "title": "Statements time per call  (pg_stat_statements) aka latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(irate(pgwatch_stat_statements_calls_total_time[$__rate_interval])) / sum(irate(pgwatch_stat_statements_calls_calls[$__rate_interval]))",
     "legendFormat": "Calls"
    }
   ]
  },
  {
   "title": "TODO: Total rows  (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "TODO: Rows per call  (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "blk_read_time vs blk_write_time (s/s) (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "sec/sec" } },
   "targets": [
    {
     "expr": "sum(irate(pgwatch_stat_statements_blk_read_time[$__rate_interval]))",
     "legendFormat": "blk_read_time"
    },
    {
     "expr": "sum(irate(pgwatch_stat_statements_blk_write_time[$__rate_interval]))",
     "legendFormat": "blk_read_time"
    }
   ]
  },
  {
   "title": "blk_read_time vs blk_write_time (s/s) per call (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "sec/sec" } },
   "targets": [
    {
     "expr": "sum(irate(pgwatch_stat_statements_blk_read_time[$__rate_interval]))/sum(irate(pgwatch_stat_statements_calls_calls[$__rate_interval]))",
     "legendFormat": "blk_read_time"
    },
    {
     "expr": "sum(irate(pgwatch_stat_statements_blk_write_time[$__rate_interval]))/sum(irate(pgwatch_stat_statements_calls_calls[$__rate_interval]))",
     "legendFormat": "blk_read_time"
    }
   ]
  },
  {
   "title": "shared_blks_hit (bytes) (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(pgwatch_stat_statements_shared_blks_hit[$__rate_interval])) * 8192",
     "legendFormat": "shared bytes"
    }
   ]
  },
  {
   "title": "shared_blks_hit (bytes) per call (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(sum(irate(pgwatch_stat_statements_shared_blks_hit[$__rate_interval])) * 8192)/sum(irate(pgwatch_stat_statements_calls_calls[$__rate_interval]))",
     "legendFormat": "shared bytes per call"
    }
   ]
  },
  {
   "title": "shared_blks_read (bytes) (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(pgwatch_stat_statements_shared_blks_read[$__rate_interval])) * 8192",
     "legendFormat": "shared bytes"
    }
   ]
  },
  {
   "title": "shared_blks_read (bytes) per call (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(sum(irate(pgwatch_stat_statements_shared_blks_read[$__rate_interval])) * 8192)/sum(irate(pgwatch_stat_statements_calls_calls[$__rate_interval]))",
     "legendFormat": "shared bytes per call"
    }
   ]
  },
  {
   "title": "shared_blks_written (bytes) (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(pgwatch_stat_statements_shared_blks_written[$__rate_interval])) * 8192",
     "legendFormat": "shared bytes"
    }
   ]
  },
  {
   "title": "shared_blks_written (bytes) per call (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(sum(irate(pgwatch_stat_statements_shared_blks_written[$__rate_interval])) * 8192)/sum(irate(pgwatch_stat_statements_calls_calls[$__rate_interval]))",
     "legendFormat": "shared bytes per call"
    }
   ]
  },
  {
   "title": "shared_blks_dirtied (bytes) (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(pgwatch_stat_statements_shared_blks_dirtied[$__rate_interval])) * 8192",
     "legendFormat": "shared bytes"
    }
   ]
  },
  {
   "title": "shared_blks_dirtied (bytes) per call (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(sum(irate(pgwatch_stat_statements_shared_blks_dirtied[$__rate_interval])) * 8192)/sum(irate(pgwatch_stat_statements_calls_calls[$__rate_interval]))",
     "legendFormat": "shared bytes per call"
    }
   ]
  },
  {
   "title": "shared_blks_read_ratio (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(irate(pgwatch_stat_statements_shared_blks_hit[$__rate_interval]))/(sum(irate(pgwatch_stat_statements_shared_blks_hit[$__rate_interval])) + sum(irate(pgwatch_stat_statements_shared_blks_read[$__rate_interval]))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WAL bytes (pg_current_wal_lsn)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(pgwatch_wal_xlog_location_b[$__rate_interval]))",
     "legendFormat": "shared bytes"
    }
   ]
  },
  {
   "title": "WAL bytes per call (pg_current_wal_lsn)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(pgwatch_wal_xlog_location_b[$__rate_interval]))/sum(irate(pgwatch_stat_statements_calls_calls[$__rate_interval]))",
     "legendFormat": "shared bytes"
    }
   ]
  },
  {
   "title": "WAL fpi (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(pgwatch_stat_statements_wal_fpi[$__rate_interval]))",
     "legendFormat": "shared bytes"
    }
   ]
  },
  {
   "title": "WAL fpi per call (pg_current_wal_lsn)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(pgwatch_stat_statements_wal_fpi[$__rate_interval]))/sum(irate(pgwatch_stat_statements_calls_calls[$__rate_interval]))",
     "legendFormat": "shared bytes"
    }
   ]
  },
  {
   "title": "temp_bytes_read vs temp_bytes_written (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(pgwatch_stat_statements_temp_blks_read[$__rate_interval]))*8192",
     "legendFormat": "Temp bytes read"
    },
    {
     "expr": "sum(irate(pgwatch_stat_statements_temp_blks_written[$__rate_interval]))*8192",
     "legendFormat": "Temp bytes written"
    }
   ]
  },
  {
   "title": "temp_bytes_read vs temp_bytes_written (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(pgwatch_stat_statements_temp_blks_read[$__rate_interval]))*8192/sum(irate(pgwatch_stat_statements_calls_calls[$__rate_interval]))",
     "legendFormat": "Temp bytes read"
    },
    {
     "expr": "sum(irate(pgwatch_stat_statements_temp_blks_written[$__rate_interval]))*8192/sum(irate(pgwatch_stat_statements_calls_calls[$__rate_interval]))",
     "legendFormat": "Temp bytes written"
    }
   ]
  },
  {
   "title": "Locks by mode",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(pgwatch_locks_mode_count[$__rate_interval]) * 60)  by (mode) > 0",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TODO: Longest non-idle transaction age, > 1 min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
   "targets": [
    {}
   ]
  },
  {
   "title": "TODO: Age of the oldest transaction ID that has not been frozen",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
   "targets": [
    {}
   ]
  },
  {
   "title": "TODO: Age of the oldest multi-transaction ID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 123 },
   "targets": [
    {}
   ]
  },
  {
   "title": "TODO: No. of pending WAL files to be archived",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 131 },
   "targets": [
    {}
   ]
  },
  {
   "title": "TODO: Number of queries stuck in idle in transaction state (>10min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 131 },
   "targets": [
    {}
   ]
  }
 ]
}