global:
  scrape_interval: 15s        # Default scrape interval
  evaluation_interval: 15s    # Default evaluation interval
  scrape_timeout: 10s         # Global scrape timeout

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'pgwatch-prometheus'
    static_configs:
      - targets: ['pgwatch-prometheus:9091']
    scrape_interval: 30s      # How often to scrape PGWatch
    scrape_timeout: 25s       # Timeout for each scrape (must be < scrape_interval)
    metrics_path: /pgwatch 