{{- if .Values.metricsServer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres-ai-monitoring.fullname" . }}-metrics-server
  namespace: {{ include "postgres-ai-monitoring.namespace" . }}
  labels:
    {{- include "postgres-ai-monitoring.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics-server
spec:
  type: {{ .Values.metricsServer.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.metricsServer.service.port | default 8000 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "postgres-ai-monitoring.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: metrics-server
{{- end }}

