{{- if .Values.nodeExporter.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "postgres-ai-monitoring.fullname" . }}-node-exporter
  namespace: {{ include "postgres-ai-monitoring.namespace" . }}
  labels:
    {{- include "postgres-ai-monitoring.labels" . | nindent 4 }}
    app.kubernetes.io/component: node-exporter
spec:
  selector:
    matchLabels:
      {{- include "postgres-ai-monitoring.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: node-exporter
  template:
    metadata:
      labels:
        {{- include "postgres-ai-monitoring.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: node-exporter
    spec:
      hostNetwork: true
      hostPID: true
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: node-exporter
          image: {{ .Values.nodeExporter.image }}
          imagePullPolicy: IfNotPresent
          args:
            - --path.rootfs=/host
            - --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)
          ports:
            - name: metrics
              containerPort: 9100
              protocol: TCP
          volumeMounts:
            - name: root
              mountPath: /host
              readOnly: true
              mountPropagation: HostToContainer
          {{- with .Values.nodeExporter.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: root
          hostPath:
            path: /
      tolerations:
        - effect: NoSchedule
          operator: Exists
{{- end }}


