{{- if .Values.pgwatchPostgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres-ai-monitoring.fullname" . }}-pgwatch-postgres
  namespace: {{ include "postgres-ai-monitoring.namespace" . }}
  labels:
    {{- include "postgres-ai-monitoring.labels" . | nindent 4 }}
    app.kubernetes.io/component: pgwatch-postgres
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "postgres-ai-monitoring.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: pgwatch-postgres
{{- end }}


