{{- if .Values.postgresExporter.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres-ai-monitoring.fullname" . }}-postgres-exporter
  namespace: {{ include "postgres-ai-monitoring.namespace" . }}
  labels:
    {{- include "postgres-ai-monitoring.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres-exporter
spec:
  type: ClusterIP
  ports:
    - port: 9187
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "postgres-ai-monitoring.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres-exporter
{{- end }}


