{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "postgres-ai-monitoring.fullname" . }}-discovery
  labels:
    {{- include "postgres-ai-monitoring.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/metrics
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources:
      - configmaps
    verbs: ["get"]
  - nonResourceURLs:
      - /metrics
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "postgres-ai-monitoring.fullname" . }}-discovery
  labels:
    {{- include "postgres-ai-monitoring.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "postgres-ai-monitoring.fullname" . }}-discovery
subjects:
  - kind: ServiceAccount
    name: {{ include "postgres-ai-monitoring.serviceAccountName" . }}
    namespace: {{ include "postgres-ai-monitoring.namespace" . }}
{{- end }}


