apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres-ai-monitoring.fullname" . }}-sink-postgres
  namespace: {{ include "postgres-ai-monitoring.namespace" . }}
  labels:
    {{- include "postgres-ai-monitoring.labels" . | nindent 4 }}
    app.kubernetes.io/component: sink-postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "postgres-ai-monitoring.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: sink-postgres


