apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "postgres-ai-monitoring.fullname" . }}-sink-postgres
  namespace: {{ include "postgres-ai-monitoring.namespace" . }}
  labels:
    {{- include "postgres-ai-monitoring.labels" . | nindent 4 }}
    app.kubernetes.io/component: sink-postgres
spec:
  serviceName: {{ include "postgres-ai-monitoring.fullname" . }}-sink-postgres
  replicas: 1
  selector:
    matchLabels:
      {{- include "postgres-ai-monitoring.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: sink-postgres
  template:
    metadata:
      labels:
        {{- include "postgres-ai-monitoring.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: sink-postgres
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: postgres
          image: {{ .Values.sinkPostgres.image }}
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_DB
              value: {{ .Values.sinkPostgres.database | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.sinkPostgres.user | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "postgres-ai-monitoring.secretName" . }}
                  key: postgres-password
            - name: POSTGRES_HOST_AUTH_METHOD
              value: "trust"
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
          {{- with .Values.sinkPostgres.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: init-scripts
          configMap:
            name: {{ include "postgres-ai-monitoring.fullname" . }}-sink-postgres-init
            defaultMode: 0755
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: {{ .Values.storage.accessModes }}
        {{- if .Values.storage.storageClassName }}
        storageClassName: {{ .Values.storage.storageClassName }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.storage.postgresSize }}


