# PGWatch Sources Configuration - PostgreSQL Instance
# This instance stores detailed metrics in PostgreSQL format

- name: target-database
  conn_str: postgresql://pgwatch_monitor:monitor_pass@target-db:5432/target_database
  kind: postgres
  custom_metrics:
    pgss_queryid_queries: 30
  custom_tags:
    env: demo
    cluster: local
    sink_type: postgresql
  is_enabled: true
  stmt_timeout: 30 